import type { Metadata } from "next";
import "./globals.css";
import { PipecatProvider } from "../providers/PipecatProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <PipecatProvider>{children}</PipecatProvider>
      </body>
    </html>
  );
}
